name: f4f
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.17
  - pip=23.2.1
  - numpy=1.25.2
  - pandas=2.0.3
  - jupyter=1.0.0
  - keras=2.12.0
  - matplotlib=3.7.1
  - scipy=1.11.1
  - seaborn=0.12.2
  - openpyxl=3.0.10
  - pip:
      - tensorflow==2.13.*
